services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_secure
      POSTGRES_DB: streamflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://user_admin:password_secure@db:5432/streamflow_db"
    depends_on:
      - db

volumes:
  postgres_data: